import pandas as pd
p1=pd.read_excel('RESPONSEDATA.xlsx','Campaign')
p2=pd.read_excel('RESPONSEDATA.xlsx','Response')
#print(p1)
#print(p2)
result = pd.merge(p1, p2, on='CampaignID', how='inner')
r=pd.DataFrame(result)
r.groupby('CampaignID')
#result.pd.groupby('CampaignID')
print(r)
writer = pd.ExcelWriter('pandas_simple.xlsx')
r.to_excel(writer,'Sheet1',index=False)
writer.save()
#print(result2)